migrate community.vmware.vmware_cluster_vcls module
ansible-collections/vmware.vmware pull request #61
Opened 2024-08-21 14:39 UTC by mikemorency

##### SUMMARY
This is a migration of the community.vmware.vmware_cluster_vcls module.

The inputs are backwards compatible. I added two inputs, `datastores_to_add` and `datastores_to_remove` to allow incremental modifications to the vCLS config. The legacy module only allowed absolute modifications; you needed to specify all allowed datastores every time.

The outputs that return any datastores added or removed by the module have changed key names to be more consistent with other output names in this collection. For example, `Added_AllowedDatastores` -> `added_datastores` 
Ive also added a new output to return the entire list of allowed datastores, `allowed_datastores`.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
cluster_vcl

##### Additional Information
Heres an example of the new output from the simulator tests:
```
{
    "added_datastores": [
        "LocalDS_0"
    ],
    "allowed_datastores": [
        "LocalDS_0"
    ],
    "changed": true,
    "invocation": {
        "module_args": {
            "allowed_datastores": [
                "LocalDS_0"
            ],
            "cluster": "DC0_C0",
            "datacenter": "DC0",
            "datastores_to_add": null,
            "datastores_to_remove": null,
            "hostname": "127.0.0.1",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 8989,
            "proxy_host": null,
            "proxy_port": null,
            "username": "user",
            "validate_certs": false
        }
    },
    "reconfig_task_result": {
        "completion_time": "2024-08-21T14:29:54.147149+00:00",
        "entity_name": "domain-c29",
        "error": null,
        "result": null,
        "state": "success"
    },
    "removed_datastores": []
}
```

2024-08-21 15:21 UTC, mariolenz reviewed
Do you _really_ want to migrate this module? [vSphere 8.0 Update 3 introduces a redesign of vCLS to Embedded vCLS, which utilizes vSphere Pod technology](https://docs.vmware.com/en/VMware-vSphere/8.0/rn/vsphere-esxi-803-release-notes/index.html).

This means that [embedded vCLS VMs (introduced in 8.0 U3) have no datastores](https://knowledge.broadcom.com/external/article/370225/scripting-impacts-of-embedded-vcls-vms-h.html). So you would migrate a module that looks to be quite useless for vSphere 8.0 U3+.

I suggest to _not_ migrate this module. You can do it, if you really want to... but personally I wouldn't. Doesn't make much sense to me. Let's keep it in `community.vmware`.

I'm not against migrating the module, but since I don't see a future for it...

2024-08-21 15:42 UTC, mikemorency commented
We have a downstream repo that uses this module, and I think for now we still need to support people using 7x. The additional testing we can do in this repo would be helpful, although i guess once we update our vcenter the tests there will be less helpful....

@machacekondra what do you think

2024-08-21 16:19 UTC, mariolenz commented
> We have a downstream repo that uses this module, and I think for now we still need to support people using 7x.

No problem, just wanted to make you aware that you're migrating a module that won't be useful for long.

I'm not sure when 7.x will go EOL. It used to be April 2025 or something like this, but I think I've read somewhere that this has been extended some 6 months or so. Can't find a link for this ATM, though :-/

> The additional testing we can do in this repo would be helpful

True.

> although i guess once we update our vcenter the tests there will be less helpful...

Also true :-)

2024-08-28 11:10 UTC, elsapassaro commented on tests/integration/targets/vmware_cluster_vcls/tasks/main.yml
> +      community.vmware.vmware_cluster:
wouldn't it be better to use `vmware.vmware.cluster` module instead now that it's merged? 

same for the task to destroy the test cluster

2024-08-28 17:27 UTC, mariolenz requested changes
Please add the new `cluster_vcls` module to the `vmware` action group in `meta/runtime.yml`.

2024-08-29 08:58 UTC, anna-savina approved these changes
LGTM

2024-09-03 12:27 UTC, merged