vm_name now not a required variable
ansible-collections/vmware.vmware pull request #93
Opened 2024-12-23 12:37 UTC by OrrBG

##### SUMMARY
Fixes: vm_name now not a required variable

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
content_template module

2024-12-23 13:18 UTC, prabinovRedhat commented
lgtm

2024-12-23 13:18 UTC, prabinovRedhat approved these changes

2024-12-23 15:07 UTC, mikemorency requested changes
`vm_name` is still required when state==present. The module needs to check for that, preferably in the argument spec definition. And the docs need to reflect that

2024-12-24 08:20 UTC, anna-savina commented
re-base branch please. You branch doesn't include changes from [92](https://github.com/ansible-collections/vmware.vmware/pull/92)

2024-12-27 18:10 UTC, mikemorency commented on plugins/modules/content_template.py
> +        vm_name=dict(type='str', required=(argument_spec['state'] == 'present')),
this is not the correct syntax, see `required-if` here 
https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec-dependencies

2024-12-31 11:24 UTC, anna-savina commented on plugins/modules/content_template.py
> -        required: true
I think it's worth mentioning that `vm_name` is required when the state is `present`. Maybe not here, but in the description.

2024-12-31 15:19 UTC, mikemorency approved these changes

2025-01-02 06:36 UTC, anna-savina commented
Remove `vm_name` from `vmware_content_template` integration test to test changes, please

https://github.com/ansible-collections/vmware.vmware/blob/8ad8eb486af67dc5b439f2ae3bea992adb35efa0/tests/integration/targets/vmware_content_template/tasks/main.yml#L72C1-L72C28

2025-01-05 09:36 UTC, anna-savina approved these changes

2025-01-05 17:45 UTC, merged